### ISSUE TITLE
`nimble develop` doesn't work; `srcDir=src` (from nimble file) doesn't exist

### ISSUE THREAD

**Issue by timotheecour** [mratsim/constantine#111]
* constantine.nimble shows
```
srcDir        = "src"
```
but `src` doesn't exit
* after `nimble develop` inside a fresh clone, `import pkg/constantine/primitives.nim` doesn't work

probably a consequence of 1st point

## related
as mentioned in https://github.com/nim-lang/RFCs/issues/267#issuecomment-716074374, omitting `src` pollutes scope (eg: I wouldn't want `import pkg/helpers/static_for` to work as other packages may define their own helpers directory; instead the src prefix is needed such that you can only access it via `import pkg/constantine/helpers/static_for`), unless https://github.com/nim-lang/RFCs/issues/291 is implemented which gives best of both worlds

**Comment by mratsim** [comment]
That's because I used to use `src` before changing.

I'm not going back to `src` as long as nimble is dropping it on installation https://github.com/nim-lang/nimble/issues/653
