### ISSUE TITLE
Bug: Disabling intel assembly causes undefined symbols

### ISSUE THREAD

**Issue by benbierens** [mratsim/constantine#301]
Seen in project codex-storage/nim-codex.
We set `use_asm_syntax_intel=false` for compatibility with secp256k1. This causes undefined symbols 'u' and 'x'. We are working around it by disabling assembly entirely.
<img width="948" alt="image" src="https://github.com/mratsim/constantine/assets/39762930/eda1381f-3d9b-47c6-9670-9f178db14aff">

**Comment by mratsim** [comment]
I can't reproduce in branch gcc-asm which default for testing to LTO = false and AT&T assembly: https://github.com/mratsim/constantine/blob/de927e398ecae29dff1c4e07ee6b99ccb07f0cad/constantine.nimble#L117-L132

CI job: https://github.com/mratsim/constantine/actions/runs/6990069731/job/19019218914

Furthermore your screenshot mentions line 303 of limbs_asm_modular_x86 but that file only has 282 lines: https://github.com/mratsim/constantine/blob/d77bb79a41b7920505f1915454c802f4d8c1977c/constantine/math/arithmetic/assembly/limbs_asm_modular_x86.nim#L280-L282

Even going back to when this file was created in April 2022, line 303 was behind `when isMainModule` and so wouldn't create an error: https://github.com/mratsim/constantine/blob/ffacf61e8a6855c009bb180a444e498d5de22b42/constantine/math/arithmetic/assembly/limbs_asm_modular_x86.nim#L284-L303
