### ISSUE TITLE
Bug: Conditional syntax error for multiplexers.nim

### ISSUE THREAD

**Issue by benbierens** [mratsim/constantine#302]
On line 150 and line 167 of multiplexers.nim (sha 5f7ba18)
```
(`*x`)
```
Replaced by
```
(*`x`)
```

**Comment by mratsim** [comment]
What Nim and C compiler are you using, and are you using LTO? Because this doesn't happen in CI and the code has been like this since forever.

**Comment by mratsim** [comment]
closed by #306
