### ISSUE TITLE
Add the Uncompressed point Serialization

### ISSUE THREAD

**Issue by advaita-saha** [mratsim/constantine#317]
# Uncompressed Serialization for Banderwagon Points

In the compressed form, we used to send only the $x$ co-ordinate of the point, along with the sign of the $y$. Then the point was reconstructed while deserialization using the curve equation.

The support for the uncompressed point serialization will help the ethereum client to save trusted points in their storage, without doing the expensive $y$ calculation

**Comment by mratsim** [comment]
Related to #236, we can probably get 30% perf improvement or so with precomputed discrete log tables for faster decompression on Banderwagon.

Though it will still be much slower than no compression.

**Comment by advaita-saha** [comment]
> Related to #236, we can probably get 30% perf improvement or so with precomputed discrete log tables for faster decompression on Banderwagon.
> 
> Though it will still be much slower than no compression.

This issue is not related to performance rather a feature to save points from trusted sources if needed. It was recommended by Ignacio to add, even though it is not a necessity. It is also implemented in the go-ipa

https://github.com/crate-crypto/go-ipa/blob/408dbffb2041271c95979a3fb79d98b268bf2880/banderwagon/element.go#L63
