### ISSUE TITLE
Followup: Go API for BLS signatures

### ISSUE THREAD

**Issue by mratsim** [mratsim/constantine#386]
https://github.com/mratsim/constantine/pull/383 has a couple of non-ideal features

- [ ] We should use size_t instead of ptrdiff_t as it's the convention in C land, even though I agree ptrdiff_t is more correct.
- [X] We have useless allocation + copy of potentially a large number of pubkeys or signatures. Allocations that we actvely try to avoid. This can be avoided by exposing the lower level BLSBatchSigAccumulator to C/Go and reimplementing aggregate-verify / serial batch-verify on top.

**Comment by Vindaar** [comment]
> #383 has a couple of non-ideal features
> 
> 1. We should use size_t instead of ptrdiff_t as it's the convention in C land, even though I agree ptrdiff_t is more correct.

Should we update all C headers to replace `ptrdiff_t` -> `size_t` while at it?

> 2. We have useless allocation + copy of potentially a large number of pubkeys or signatures. Allocations that we actvely try to avoid. This can be avoided by exposing the lower level BLSBatchSigAccumulator to C/Go and reimplementing aggregate-verify / serial batch-verify on top.

Looking at `BlsBatchSigAccumulator` right now I'm a bit unsure about how we expose it to C given the extremely generic (incl. `static`) nature. We define a non-generic version in Nim, which we expose to C? With the explicit types required for the BLS sig use case, similar to how `PublicKey` and friends are defined?

**Comment by Vindaar** [comment]
I implemented 2 in PR #383 now. 

Nim code with new type and functions: https://github.com/mratsim/constantine/pull/383/commits/3139fb82ac7f2fc3c674b43f12b9247e5c7a5d99

C definitions: 
https://github.com/mratsim/constantine/pull/383/commits/ec467f60ecc6652086139b55fbf931592aa0a8d6

Horrific struct definitions taken from Nim compiler geneated C code:
https://github.com/mratsim/constantine/pull/383/commits/aed59760999944fa6fd77727218f9bcf40830589

And the Go implementation of BatchVerify:
https://github.com/mratsim/constantine/pull/383/commits/06a586e5125b5481938d9fe69492382585064654

Just mentioning it here for completeness.
