### ISSUE TITLE
Please implement pairing inversion for some curves

### ISSUE THREAD

**Issue by ytrezq** [mratsim/constantine#488]
https://pdfupload.io/docs/8453308d#%5B%7B%22num%22%3A2790%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22FitH%22%7D%2C343%5D shows how certain type of pairings can be inverted in subexponential time.

I’m also interested in the case where exponention inversion is already done (so just miller inversion).

**Comment by mratsim** [comment]
The paper reduces the pairing inversion problem to discrete logarithm on field.
![image](https://github.com/user-attachments/assets/4eabe17e-f785-4b4a-9e4b-f985ceb5b81b)

but as mention in the conclusion, the discrete logarithm is still a hard problem
![image](https://github.com/user-attachments/assets/b14e1031-f468-44a1-a0b4-aaf5426a1666)

For now, I don't see any possibility of succeeding so closing the issue.

Besides, you've been opening many issues to many cryptographic libraries
![image](https://github.com/user-attachments/assets/09bc445a-8864-48d0-9d1b-5b547b696785)
![image](https://github.com/user-attachments/assets/0cf6fc7f-1157-43ac-9d81-37c0084cde79)
![image](https://github.com/user-attachments/assets/e717cfd7-0cdd-4278-8113-81d46a832853)
![image](https://github.com/user-attachments/assets/3d862763-5ad6-4059-ba78-70e378bd1908)

what is your goal?
